version: '3.8'

services:

 RecommenderDB:
  image: mysql:latest
  restart: always
  environment:
   MYSQL_DATABASE: 'RecommenderDB'
   MYSQL_USER: 'user'
   MYSQL_PASSWORD: 'recommender'
   MYSQL_ROOT_PASSWORD: 'password'
   MYSQL_TCP_PORT: 3333

  ports:
   - '3333:3333'
  expose:
   - '3333'
  volumes:
   - recommenderdb:/var/lib/mysql3

volumes:
 recommenderdb: